### ISSUE TITLE
Inference not working: `getOrElse` + `never`

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/fp-ts#1034] opened 2019-12-02 14:14 UTC
## 🐛 Bug report

```ts
import * as O from 'fp-ts/lib/Option';
import { pipe } from 'fp-ts/lib/pipeable';

declare const myOptionOption: O.Option<O.Option<string>>;

// Expected: `Option<string>`
// Actual: `Option<never>`
const result = pipe(
    // Error here with `strictFunctionTypes`
    myOptionOption,
    O.getOrElse(() => O.none),
);
```

Another example is when using [`RemoteData`](https://github.com/devexperts/remote-data-ts):

```ts
import * as RemoteData from '@devexperts/remote-data-ts';
import * as O from 'fp-ts/lib/Option';
import { pipe } from 'fp-ts/lib/pipeable';

declare const myRemoteDataOption: O.Option<RemoteData.RemoteData<
    string,
    number[]
>>;

// Expected: `RemoteData.RemoteData<string, number[]>`
// Actual: `RemoteData.RemoteData<never, never>`
const result = pipe(
    // Error here with `strictFunctionTypes`
    myRemoteDataOption,
    O.getOrElse(() => RemoteData.initial),
);
```

### Your environment

Which versions of fp-ts are affected by this issue? Did this work in previous versions of fp-ts?

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      | 2.1.1           |
| TypeScript | 3.6.4           |

**Comment by raveclassic** [comment] 2019-12-02 14:32
Duplicate of https://github.com/gcanti/fp-ts/issues/1002?

**Comment by OliverJAsh** [comment] 2019-12-02 14:34
I don't believe so. That issue was a suggestion to widen the return type, but IIUC, that's not what I'm asking for here.

**Comment by raveclassic** [comment] 2019-12-02 15:06
This is not a bug but rather the consequence of the behaviour described in #1002. 
`TypeScript` cannot assign `Option<string>` to `Option<never>` because obviously it cannot assign `string` to `never`. If `getOrElse` could widen the type this would result `Option<string> | Option<never>` which essentially is `Option<string>`.

**Comment by OliverJAsh** [comment] 2019-12-02 16:56
I guess I'm expecting TypeScript to infer the generics differently, so that this explicit generic workaround isn't needed—TypeScript should infer this for us:

```ts
        // Workaround:
        O.getOrElse<O.Option<string>>(() => O.none),
```

**Comment by gcanti** [comment] 2019-12-02 17:38
> I guess I'm expecting TypeScript to infer the generics differently

@OliverJAsh see https://github.com/gcanti/fp-ts/issues/1028#issuecomment-559008886

**Closed** 2020-01-11 17:12 UTC
