### ISSUE TITLE
chainFirst not allowing access to the first result

### ISSUE THREAD

**Issue by rtoyias** [gcanti/fp-ts#877] opened 2019-05-24 17:56 UTC
**Do you want to request a _feature_ or report a _bug_?**
Not sure.  There is a good chance I'm just doing this wrong.

**What is the current behavior?**
I am trying to do something like the following where the result of the first chained function are used by the second but we pass along the result of the first.

```
it('chainFirst', () => {
    const log: Array<string> = []
    const append = (message: string, millis: number): TaskEither<string, string> =>
      right(delay(millis, undefined).map(() => log.push(message).toString() ))
    return append('a', 10)
      .chainFirst( x => append(x, 0) )
      .run()
      .then(e => {
        assert.deepStrictEqual(e, eitherRight('1'))
        assert.deepStrictEqual(log, ['a', '1'])
      })
  })
```

Currently the above test gives the following error 
```
Argument of type '(x: any) => TaskEither<string, string>' is not assignable to parameter of type 'TaskEither<string, {}>'.
  Type '(x: any) => TaskEither<string, string>' is missing the following properties from type 'TaskEither<string, {}>': value, _A, _L, _URI, and 21 more.ts(2345)
```
Am I doing this incorrectly or is this a bug?

Thanks

Rob

using fp-ts version v 1.17.2

**Comment by gcanti** [comment] 2019-06-11 16:20
@rtoyias it's not a bug, `chainFirst` is defined as

```ts
chainFirst<B>(fb: TaskEither<L, B>): TaskEither<L, A>
```

so it accepts a value rather than a callback.

This will be fixed in v1.19.0 in a backward compatible way (i.e. adding a top level `chainFirst` function).

**Closed** 2019-06-12 22:13 UTC
