### ISSUE TITLE
Node 10 DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/fp-ts#545] opened 2018-08-12 08:28 UTC
Using Node 10, I get this warning when logging an `option`:

```
DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
```

I believe this is because the type implements an `inspect` function, which is used to format the string when logging.

We should update this to instead use the new symbol based API: https://nodejs.org/api/util.html#util_custom_inspection_functions_on_objects

**Comment by gcanti** [comment] 2018-08-12 13:43
Duplicate of https://github.com/gcanti/fp-ts/issues/408

**Closed by gcanti** 2018-08-12 13:43 UTC
Labels: duplicate
