### ISSUE TITLE
Piping with sum types broken?

### ISSUE THREAD

**Issue by christianbradley** [gcanti/fp-ts#1028] opened 2019-11-25 05:17 UTC
### Current Behavior

In fp-ts@1.x, I was able to chain sum typed values through methods that returned any one of the union's members (see the contrived example below). Starting with 2.x, using `pipe` and `chain`, I am getting type errors on the first argument 

```typescript
// contrived example
import { chain, either, fromPredicate } from 'fp-ts/lib/Either'
import { pipe } from 'fp-ts/lib/pipeable'

type InvalidPositive = ["InvalidPositive", number];
type InvalidInteger = ["InvalidInteger", number];

type InvalidPositiveInteger = InvalidPositive | InvalidInteger;

const positive = fromPredicate(
  (n: number) => n > 0,
  (a): InvalidPositive => ["InvalidPositive", a]
);

const integer = fromPredicate(
  (n: number) => Number.isInteger(n),
  (a): InvalidInteger => ["InvalidInteger", a]
);

pipe(
  either.of<InvalidPositiveInteger, number>(2), // <<< Type exception here
  chain(positive),
  chain(integer)
);

/**
Type exception I get is:

Argument of type 'Either<InvalidPositiveInteger, number>' is not assignable to parameter of type 'Either<["InvalidPositive", number], number>'.
  Type 'Left<InvalidPositiveInteger>' is not assignable to type 'Either<["InvalidPositive", number], number>'.
    Type 'Left<InvalidPositiveInteger>' is not assignable to type 'Left<["InvalidPositive", number]>'.
      Type 'InvalidPositiveInteger' is not assignable to type '["InvalidPositive", number]'.
        Type '["InvalidInteger", number]' is not assignable to type '["InvalidPositive", number]'.
          Type '"InvalidInteger"' is not assignable to type '"InvalidPositive"'.ts(2345)

**/
```

I can only solve this by specifying the sum type in each call to chain like so:

```typescript
pipe(
  either.of<InvalidPositiveInteger, number>(2),
  chain<InvalidPositiveInteger, number, number>(positive),
  chain<InvalidPositiveInteger, number, number>(integer)
);
```

### Expected behavior

I expect sum types to be able to pipe to methods that return union set members without causing type exceptions.

### Your environment

Which versions of fp-ts are affected by this issue? Did this work in previous versions of fp-ts?

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |      2.1.x      |
| TypeScript |  3.6.x          |

**Comment by gcanti** [comment] 2019-11-26 17:12
Closing in favor of https://github.com/gcanti/fp-ts/issues/904

**Closed by gcanti** 2019-11-26 17:12 UTC

**Comment by christianbradley** [comment] 2019-11-26 18:46
@gcanti - not sure this should be closed in favor of #904 . Though they are similar issues, they are not the same problem.

#904 is about automatically widening "Lefts" on Eithers, this one is about the interface of pipe and chain not accepting valid values. Notably, #904 would still be applicable in v1.x, while this issue was not present in the previous "class-based" version of Either/TaskEither/IOEither etc.

If I start with an `Either<L | M, A>` I should be able to chain it to a method that returns `Either<L, A>` or `Either<M, A>`. I should not need to "widen" type types down the pipeline.

Correct me if I'm wrong, but I believe this is an issue with either `pipe` or `chain`'s interface definition(s). 

Thoughts?

**Comment by christianbradley** [comment] 2019-11-26 19:02
To my point, the following does not cause a type exception:

```typescript
pipe(
  either.of<InvalidPositiveInteger, number>(2),
  ma => either.chain(ma, positive),
  mb => either.chain(mb, integer)
);
```

While this does:

```typescript
e = pipeable(either)

pipe(
    either.of<InvalidPositiveInteger, number>(2),
    e.chain(positive),
    e.chain(integer)
)
```

**Comment by gcanti** [comment] 2019-11-27 09:39
@christianbradley the issue is the same: TypeScript type inference goes from left to right:

in

```ts
pipe(
  either.of<InvalidPositiveInteger, number>(2),
  ma => either.chain(ma, positive),
  mb => either.chain(mb, integer)
)
```

TypeScript infers

```ts
pipe(
  either.of<InvalidPositiveInteger, number>(2),
  // ma: Either<InvalidPositiveInteger, number>
  ma => either.chain<InvalidPositiveInteger, number, number>(ma, positive),
  // mb: Either<InvalidPositiveInteger, number>
  mb => either.chain<InvalidPositiveInteger, number, number>(mb, integer)
)
```

because, going from left to right, `ma` has type `Either<InvalidPositiveInteger, number>`, so `chain` is inferred as

```ts
chain<InvalidPositiveInteger, number, number>
```

however in 

```ts
pipe(
  either.of<InvalidPositiveInteger, number>(2),
  e.chain(positive),
  e.chain(integer)
)
```

TypeScript infers

```ts
pipe(
  either.of<InvalidPositiveInteger, number>(2),
  e.chain<InvalidPositive, number, number>(positive),
  e.chain<InvalidInteger, number, number>(integer)
)
```

because `e.chain` has the following signature

```ts
chain: <E, A, B>(f: (a: A) => Either<E, B>) => (ma: Either<E, A>) => Either<E, B>
```

so in our case, going from left to right, the first `e.chain` has the following type

```ts
//      +-- E inferred as InvalidPositive
//      |
//      v                  this doesn't type check because E is already inferred as InvalidPositive  ------v
chain: <InvalidPositive, number, number>(f: (a: number) => Either<InvalidPositive, number>) => (ma: Either<InvalidPositiveInteger, number>) => Either<E, B>
```
